# Generated by Django 4.0.4 on 2022-04-15 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('genre', models.CharField(default='', max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('poster', models.ImageField(upload_to='games/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм айди')),
                ('nickname', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Имя')),
                ('prefered_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Игроки', to='tgamer_app.game', verbose_name='Любимая игра')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
