# Generated by Django 4.0.4 on 2022-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgamer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='search_enabled',
            field=models.BooleanField(default=True, verbose_name='Поиск включен'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(upload_to='media/games/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
