# Generated by Django 4.0.4 on 2022-04-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgamer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='telegram_id',
            new_name='tg_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='sign_up',
            field=models.IntegerField(choices=[(1, 'Steam Name'), (2, 'About'), (3, 'Prefered Game'), (4, 'Done')], default=1),
        ),
    ]
