# Generated by Django 4.0.4 on 2022-04-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgamer_app', '0003_alter_player_sign_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='steam_nickname',
            new_name='steam_name',
        ),
    ]
